const HOST = 'https://www.bitstamp.net';
const REQUEST_TIMEOUT = 5000;
const TYPE_SELL_ORDER = 'sell';
const TYPE_BUY_ORDER = 'buy';

const TYPE_DEPOSIT = 0;
const TYPE_WITHDRAWAL = 1;
const TYPE_MARKET_TRADE = 2;

module.exports = {
  HOST: HOST,
  REQUEST_TIMEOUT: REQUEST_TIMEOUT,
  TYPE_SELL_ORDER: TYPE_SELL_ORDER,
  TYPE_BUY_ORDER: TYPE_BUY_ORDER,
  TYPE_DEPOSIT: TYPE_DEPOSIT,
  TYPE_WITHDRAWAL: TYPE_WITHDRAWAL,
  TYPE_MARKET_TRADE: TYPE_MARKET_TRADE
};
